# Generated by Django 3.2 on 2024-07-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video', models.FileField(upload_to='videos/')),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.CharField(max_length=255)),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
