# Generated by Django 3.2 on 2024-07-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0002_auto_20240722_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='country',
            field=models.CharField(default='kr', max_length=10),
        ),
    ]
